name: Deploy to ReetuGoel GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    # Only run this workflow when pushing to the ReetuGoel repository
    if: github.repository == 'ReetuGoel/ergowiseAI'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Ensure correct homepage for ReetuGoel deployment
      run: |
        npm pkg set homepage="https://ReetuGoel.github.io/ergowiseAI"
        echo "Homepage set to: $(npm pkg get homepage)"
    
    - name: Build application
      run: npm run build
    
    - name: Setup Git config
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    
    - name: Create gh-pages branch if it doesn't exist
      run: |
        git fetch origin
        if ! git rev-parse --verify origin/gh-pages >/dev/null 2>&1; then
          echo "Creating gh-pages branch..."
          git checkout --orphan gh-pages
          git rm -rf .
          echo "<!DOCTYPE html><html><head><title>ErgoWise AI</title></head><body><h1>Setting up ErgoWise AI...</h1></body></html>" > index.html
          git add index.html
          git commit -m "Initial gh-pages commit"
          git push origin gh-pages
          git checkout main
        fi
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        force_orphan: false
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'Deploy ErgoWise to GitHub Pages'
        enable_jekyll: false