name: Deploy to ReetuGoel GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    # Only run this workflow when pushing to the ReetuGoel repository
    if: github.repository == 'ReetuGoel/ergowiseAI'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Ensure correct homepage for ReetuGoel deployment
      run: |
        npm pkg set homepage="https://ReetuGoel.github.io/ergowiseAI"
        echo "Homepage set to: $(npm pkg get homepage)"
    
    - name: Build application
      run: npm run build
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        force_orphan: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'Deploy ErgoWise to GitHub Pages'